export const JAZZ_HISTORY = [
  {
    period: '1900s – 1920s',
    title: 'Early Roots',
    summary: 'From banjo to guitar in the earliest jazz bands.',
    details: "Jazz's first guitarists mostly doubled on banjo, prized for cutting through a horn-heavy band without amplification. As recording technology improved through the 1910s and 20s, the guitar's warmer, quieter tone slowly won favor for blending rather than cutting. These players were almost entirely rhythm players — strumming through changes, keeping time, rarely stepping into a solo role.",
    keyArtists: ['Johnny St. Cyr', 'Bud Scott'],
    listenFor: 'Steady four-to-the-bar strumming, no amplification, guitar sitting deep in the rhythm section.',
  },
  {
    period: '1920s – early 1930s',
    title: 'The Rhythm Guitar Era',
    summary: 'The guitar earns its place as a serious rhythm instrument.',
    details: "Eddie Lang is widely considered jazz guitar's first true star — his clean, driving rhythm playing and occasional melodic runs with violinist Joe Venuti showed the instrument could do more than just keep time. Lonnie Johnson, working across blues and jazz, pushed single-note lines further than almost anyone of his era. Guitar duets and small-group recordings became genuinely popular for the first time.",
    keyArtists: ['Eddie Lang', 'Lonnie Johnson'],
    listenFor: "Lang and Venuti's interplay — a rhythm guitarist starting to sound like a genuine musical voice.",
  },
  {
    period: '1930s',
    title: 'Amplification Arrives',
    summary: 'The electric guitar changes what the instrument can do.',
    details: "Before amplification, an acoustic guitar simply couldn't compete in volume with horns and drums — it was locked into a background role by physics. The electric guitar, commercialized through the early-to-mid 1930s, removed that ceiling entirely. For the first time, a guitarist could be heard clearly while soloing over a full band, not just when everyone else went quiet.",
    keyArtists: ['George Barnes', 'Les Paul (early career)'],
    listenFor: 'Recordings from this decade where the guitar suddenly sits at the same volume as the horns.',
  },
  {
    period: 'Late 1930s – 1940s',
    title: 'Charlie Christian & the Swing Revolution',
    summary: 'The single-note solo guitarist is born.',
    details: "Charlie Christian, playing with the Benny Goodman Sextet, is the single most important figure in this story. He proved an electric guitar could solo like a horn player — long, swinging single-note lines with real melodic authority, not just chords. His influence is so foundational that nearly every jazz guitarist since traces some lineage back to his brief but explosive career.",
    keyArtists: ['Charlie Christian'],
    listenFor: '"Solo Flight" and his Benny Goodman Sextet recordings — the blueprint for jazz guitar soloing.',
  },
  {
    period: '1940s – 1950s',
    title: 'Bebop Harmony',
    summary: 'Denser chords for a faster, harmonically richer music.',
    details: "As bebop pushed jazz harmony into more complex territory, guitarists needed a bigger chord vocabulary to keep up. Tal Farlow and Jimmy Raney developed fast, horn-like bebop lines alongside richer chord voicings — extensions, alterations, faster harmonic movement. This is roughly where the chord vocabulary in this app's Voicings tab has its roots.",
    keyArtists: ['Tal Farlow', 'Jimmy Raney'],
    listenFor: 'Fast, angular single-note lines that outline complex chord changes at speed.',
  },
  {
    period: '1950s',
    title: 'Cool Jazz & Chord-Melody',
    summary: 'A more introspective, harmonically sophisticated style.',
    details: "Jim Hall and Barney Kessel brought a quieter, more spacious approach — fewer notes, chosen more carefully, with real attention to touch and tone. This era also saw chord-melody playing mature: a single guitarist stating both the harmony and the tune simultaneously, essentially playing the role of a one-person rhythm section and horn line at once.",
    keyArtists: ['Jim Hall', 'Barney Kessel'],
    listenFor: 'Space between notes — cool-era players often say as much with silence as with sound.',
  },
  {
    period: 'Late 1950s – 1960s',
    title: 'The Wes Montgomery Era',
    summary: 'Octaves, thumb-picking, and enormous influence.',
    details: "Wes Montgomery played almost entirely with his bare thumb rather than a pick, giving his sound a rounder warmth still instantly recognizable today. His use of octave-doubled melody lines became one of the most imitated techniques in jazz guitar history. Largely self-taught, his influence on the generations that followed is difficult to overstate.",
    keyArtists: ['Wes Montgomery'],
    listenFor: '"Four on Six" — octave melodies and that unmistakable thumb-driven warmth.',
  },
  {
    period: '1960s – 1970s',
    title: 'Post-Bop Mastery',
    summary: 'Solo guitar arrangements reach new heights of complexity.',
    details: "Joe Pass took chord-melody playing to its logical extreme — full solo jazz guitar arrangements with walking bass lines, chords, and melody all happening simultaneously under one set of hands. George Benson, meanwhile, bridged jazz virtuosity with soul and pop sensibility, bringing jazz guitar to a much wider audience.",
    keyArtists: ['Joe Pass', 'George Benson'],
    listenFor: "Pass's solo album \"Virtuoso\" — one guitar doing the job of an entire band.",
  },
  {
    period: '1970s – 1980s',
    title: 'Fusion & Expansion',
    summary: 'Jazz guitar absorbs rock, funk, and new harmonic ideas.',
    details: "Pat Metheny and John McLaughlin pushed jazz guitar into new territory — expanded harmony, new technologies (like guitar synthesizers), and rhythmic influences borrowed from rock and world music. This era broadened what \"jazz guitar\" could even mean, moving well beyond the swing-and-bebop vocabulary of earlier decades.",
    keyArtists: ['Pat Metheny', 'John McLaughlin'],
    listenFor: 'Extended harmonic palettes and rhythmic complexity borrowed from outside the jazz tradition.',
  },
  {
    period: '1990s – Today',
    title: 'Modern Jazz Guitar',
    summary: 'A living tradition still being written.',
    details: "Contemporary players like Kurt Rosenwinkel and Julian Lage continue building on everything before them — bebop vocabulary, Wes-style octaves, fusion-era harmonic ambition — while adding their own voice. Jazz guitar today draws on over a century of development, and this app's Voicings, Scales, and Progressions tabs all carry echoes of that entire lineage.",
    keyArtists: ['Kurt Rosenwinkel', 'Julian Lage'],
    listenFor: 'Familiar bebop and swing DNA, filtered through modern harmonic and technical vocabulary.',
  },
];
